Repository YaroslavBerezin/SurfWebStudyJam2022, pull requests merged in 2023-02, with the labels that each got.

#17 TASK-54 Add advanced exception support
  core/build.gradle.kts
  core/src/main/kotlin/ru/surf/core/controller/GlobalExceptionHandler.kt
  core/src/main/kotlin/ru/surf/core/dto/ErrorDto.kt
  core/src/main/kotlin/ru/surf/core/exception/ExceptionType.kt
  core/src/main/kotlin/ru/surf/core/exception/base/CoreServiceException.kt
  core/src/main/kotlin/ru/surf/core/exception/event/EventNotFoundByIdException.kt
  core/src/main/kotlin/ru/surf/core/service/impl/EventServiceImpl.kt
Labels: enhancement

#20 TASK-50 Add files logic
  external-files/build.gradle.kts
  external-files/docker-compose.yaml
  external-files/src/main/kotlin/ru/surf/externalfiles/ExternalFilesApplication.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/configuration/S3Configuration.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/configuration/S3PropertiesConfiguration.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/configuration/SwaggerConfiguration.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/controller/ResourceController.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/controller/S3FileController.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/entity/Account.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/entity/Answer.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/entity/Candidate.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/entity/Event.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/entity/EventType.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/entity/Question.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/entity/QuestionType.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/entity/Role.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/entity/S3File.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/entity/StateType.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/entity/StatesEvents.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/entity/SurfEmployee.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/entity/Team.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/entity/TeamFeedback.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/entity/Test.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/entity/Trainee.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/entity/TraineeFeedback.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/entity/base/BaseEntity.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/entity/base/UUIDBasedEntity.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/enum/FileExtension.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/exception/ExternalServiceException.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/mapper/S3FileMapper.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/mapper/S3FileMapperImpl.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/repository/S3FileRepository.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/service/ResourceFileService.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/service/S3DatabaseService.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/service/S3FileService.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/service/impl/ResourceFileServiceImpl.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/service/impl/S3DatabaseServiceImpl.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/service/impl/S3FileServiceImpl.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/util/FileUtil.kt
  external-files/src/main/resources/application.yml
  external-files/src/main/resources/db/migration/V1.0.0__initial_script.sql
  external-files/src/main/resources/db/migration/V1.0__initial_script.sql
Labels: enhancement

#22 TASK-55 Add-kafka-integration
  core/build.gradle.kts
  core/docker-compose.yml
  core/src/main/kotlin/ru/surf/core/CoreApplication.kt
  core/src/main/kotlin/ru/surf/core/configuration/KafkaProducerConfiguration.kt
  core/src/main/kotlin/ru/surf/core/configuration/KafkaTopicConfiguration.kt
  core/src/main/kotlin/ru/surf/core/dto/GeneralNotificationDto.kt
  core/src/main/kotlin/ru/surf/core/service/KafkaService.kt
  core/src/main/kotlin/ru/surf/core/service/impl/KafkaServiceImpl.kt
  core/src/main/resources/application.yml
Labels: enhancement

#25 TASK-143 Fix-migration-scheme
  core/src/main/kotlin/ru/surf/core/entity/Candidate.kt
  core/src/main/resources/db/migration/V1.0.0__initial_script.sql
  web/angular.json
Labels: fix

#26 TASK-56 add domain module
  core/build.gradle.kts
  core/src/main/kotlin/ru/surf/core/entity/Account.kt
  core/src/main/kotlin/ru/surf/core/entity/Answer.kt
  core/src/main/kotlin/ru/surf/core/entity/Candidate.kt
  core/src/main/kotlin/ru/surf/core/entity/Event.kt
  core/src/main/kotlin/ru/surf/core/entity/EventType.kt
  core/src/main/kotlin/ru/surf/core/entity/Question.kt
  core/src/main/kotlin/ru/surf/core/entity/QuestionType.kt
  core/src/main/kotlin/ru/surf/core/entity/Role.kt
  core/src/main/kotlin/ru/surf/core/entity/StateType.kt
  core/src/main/kotlin/ru/surf/core/entity/StatesEvents.kt
  core/src/main/kotlin/ru/surf/core/entity/SurfEmployee.kt
  core/src/main/kotlin/ru/surf/core/entity/Team.kt
  core/src/main/kotlin/ru/surf/core/entity/TeamFeedback.kt
  core/src/main/kotlin/ru/surf/core/entity/Test.kt
  core/src/main/kotlin/ru/surf/core/entity/Trainee.kt
  core/src/main/kotlin/ru/surf/core/entity/TraineeFeedback.kt
  domain/build.gradle.kts
  domain/gradle/wrapper/gradle-wrapper.properties
  domain/settings.gradle.kts
  domain/src/main/kotlin/ru/surf/core/entity/Account.kt
  domain/src/main/kotlin/ru/surf/core/entity/Answer.kt
  domain/src/main/kotlin/ru/surf/core/entity/Candidate.kt
  domain/src/main/kotlin/ru/surf/core/entity/Event.kt
  domain/src/main/kotlin/ru/surf/core/entity/EventType.kt
  domain/src/main/kotlin/ru/surf/core/entity/Question.kt
  domain/src/main/kotlin/ru/surf/core/entity/QuestionType.kt
  domain/src/main/kotlin/ru/surf/core/entity/Role.kt
  domain/src/main/kotlin/ru/surf/core/entity/StateType.kt
  domain/src/main/kotlin/ru/surf/core/entity/StatesEvents.kt
  domain/src/main/kotlin/ru/surf/core/entity/SurfEmployee.kt
  domain/src/main/kotlin/ru/surf/core/entity/Team.kt
  domain/src/main/kotlin/ru/surf/core/entity/TeamFeedback.kt
  domain/src/main/kotlin/ru/surf/core/entity/Test.kt
  domain/src/main/kotlin/ru/surf/core/entity/Trainee.kt
  domain/src/main/kotlin/ru/surf/core/entity/TraineeFeedback.kt
  domain/src/main/kotlin/ru/surf/core/entity/base/BaseEntity.kt
  domain/src/main/kotlin/ru/surf/core/entity/base/UUIDBasedEntity.kt
  settings.gradle.kts
Labels: fix

#27 TASK-210 Refactor domain model in ExternalFiles module
  external-files/build.gradle.kts
  external-files/src/main/kotlin/ru/surf/externalfiles/controller/ResourceController.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/entity/Account.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/entity/Answer.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/entity/Candidate.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/entity/Event.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/entity/EventType.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/entity/Question.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/entity/QuestionType.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/entity/Role.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/entity/S3File.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/entity/StateType.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/entity/StatesEvents.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/entity/SurfEmployee.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/entity/Team.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/entity/TeamFeedback.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/entity/Test.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/entity/Trainee.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/entity/TraineeFeedback.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/entity/base/BaseEntity.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/entity/base/UUIDBasedEntity.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/service/impl/ResourceFileServiceImpl.kt
Labels: refactor

#29 TASK-90 Fix kafka issues
  core/docker-compose.yml
  core/src/main/kotlin/ru/surf/core/configuration/KafkaTopicConfiguration.kt
  core/src/main/resources/application.yml
Labels: fix

#31 TASK-250 Fix consumer offsets topic issues
  core/docker-compose.yml
  core/src/main/resources/application.yml
Labels: fix

#30 TASK-65 Add night theme
  web/src/app/app.component.html
  web/src/app/app.component.less
  web/src/app/app.component.ts
  web/src/app/app.module.ts
  web/src/app/component/enroll/enroll-applyment/step-form/step-form.component.less
  web/src/app/component/enroll/enroll-welcome/enroll-welcome.component.less
  web/src/assets/logo.svg
  web/src/styles.less
Labels: enhancement

#32 TASK-66 Add resume save logic
  .run/ExternalFilesApplication.run.xml
  core/build.gradle.kts
  core/src/main/kotlin/ru/surf/core/configuration/HessianConfiguration.kt
  core/src/main/kotlin/ru/surf/core/dto/CandidateDto.kt
  core/src/main/kotlin/ru/surf/core/mapper/candidate/impl/CandidateMapperImpl.kt
  core/src/main/kotlin/ru/surf/core/mapper/event/impl/EventMapperImpl.kt
  core/src/main/kotlin/ru/surf/core/service/impl/CandidateServiceImpl.kt
  core/src/main/resources/application.yml
  domain/src/main/kotlin/ru/surf/core/entity/Candidate.kt
  domain/src/main/kotlin/ru/surf/core/enum/ExceptionType.kt
  external-files/build.gradle.kts
  external-files/docker-compose.yaml
  external-files/src/main/kotlin/ru/surf/externalfiles/ExternalFilesApplication.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/configuration/CorsConfiguration.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/configuration/HessianConfiguration.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/controller/ResourceController.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/controller/S3FileController.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/dto/PostResponseResumeDto.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/entity/S3File.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/exception/ExternalServiceException.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/exception/S3FileNotFoundException.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/exception/base/ExternalFileServiceException.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/mapper/S3FileMapper.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/mapper/S3FileMapperImpl.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/mapper/impl/S3FileMapperImpl.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/repository/S3FileRepository.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/service/ResourceFileService.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/service/S3DatabaseService.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/service/S3FileService.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/service/impl/ResourceFileServiceImpl.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/service/impl/S3DatabaseServiceImpl.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/service/impl/S3FileServiceImpl.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/util/FileUtil.kt
  external-files/src/main/resources/application-dev.yml
  external-files/src/main/resources/application.yml
  external-files/src/main/resources/db/migration/V1.0.0__initial_script.sql
  web/src/app/component/enroll/enroll-applyment/enroll-applyment.component.html
  web/src/app/component/enroll/enroll-applyment/enroll-applyment.component.less
  web/src/app/component/enroll/enroll-applyment/enroll-applyment.component.ts
  web/src/app/entity/candidate.ts
  web/src/app/entity/s-file.spec.ts
  web/src/app/entity/s-file.ts
  web/src/app/service/resource.service.spec.ts
  web/src/app/service/resource.service.ts
Labels: enhancement

#33 TASK-67 Add Spring Cloud Gateway
  api-gateway/build.gradle.kts
  api-gateway/gradle/wrapper/gradle-wrapper.properties
  api-gateway/settings.gradle.kts
  api-gateway/src/main/kotlin/ru/surf/apigateway/ApiGatewayApplication.kt
  api-gateway/src/main/kotlin/ru/surf/apigateway/configuration/ApplicationPortsConfiguration.kt
  api-gateway/src/main/kotlin/ru/surf/apigateway/configuration/CorsConfiguration.kt
  api-gateway/src/main/kotlin/ru/surf/apigateway/configuration/RouteConfiguration.kt
  api-gateway/src/main/resources/application.yml
  api-gateway/src/test/kotlin/ru/surf/apigateway/ApiGatewayApplicationTests.kt
  settings.gradle.kts
Labels: enhancement

#28 TASK-7 dockerizing
  .run/ExternalFilesApplication.run.xml
  .run/SurfWebStudyJam2022 [_core_bootJar].run.xml
  .run/docker-compose.yml.auth-service_ Compose Deployment.run.xml
  .run/docker-compose.yml.core_service_ Compose Deployment.run.xml
  .run/docker-compose.yml.external-files-service_ Compose Deployment.run.xml
  api-gateway/Dockerfile
  api-gateway/src/main/resources/application-dev.yml
  api-gateway/src/main/resources/application-prod.yml
  auth/src/main/resources/application-dev.yml
  auth/src/main/resources/application-prod.yml
  core/Dockerfile
  core/docker-compose.yml
  core/src/main/resources/application-dev.yml
  core/src/main/resources/application-prod.yml
  core/src/main/resources/db/migration/core/V1.0.0__initial_script.sql
  defenceOfProject/Dockerfile
  defenceOfProject/src/main/resources/application-prod.yml
  defenceOfProject/src/main/resources/application.properties
  docker-compose.yml
  docker/docker-compose.yml
  domain/src/main/kotlin/ru/surf/core/entity/Candidate.kt
  external-files/Dockerfile
  external-files/docker-compose.yaml
  external-files/src/main/resources/application-dev.yml
  external-files/src/main/resources/application-prod.yml
  external-files/src/main/resources/application.yml
  external-files/src/main/resources/db/migration/external-files/V1.0.0__initial_script.sql
  mail/Dockerfile
  mail/src/main/resources/application-prod.yml
  mail/src/main/resources/application.yml
  quiz/Dockerfile
  quiz/src/main/resources/application-prod.yml
  quiz/src/main/resources/application.yml
  report/Dockerfile
  report/src/main/resources/application-prod.yml
  report/src/main/resources/application.yml
  testing/Dockerfile
  testing/src/main/resources/application.yml
  testing/src/main/resources/application_prod.yml
Labels: refactor

#35 TASK-71 auth service enhancement
  auth/src/main/kotlin/ru/surf/auth/AuthServiceApplication.kt
  auth/src/main/kotlin/ru/surf/auth/configuration/KeycloakConfiguration.kt
  auth/src/main/kotlin/ru/surf/auth/service/impl/AuthServiceImpl.kt
  auth/src/main/kotlin/ru/surf/auth/service/impl/JwtServiceImpl.kt
  auth/src/main/resources/application-dev.yml
  auth/src/main/resources/application-prod.yml
Labels: refactor

#36 TASK-72 spring cloud routing
  .run/docker-compose-local.yml.auth-service_ Compose Deployment.run.xml
  .run/docker-compose-local.yml.core-service_ Compose Deployment.run.xml
  .run/docker-compose-local.yml.defence-service_ Compose Deployment.run.xml
  .run/docker-compose-local.yml.external-files-service_ Compose Deployment.run.xml
  .run/docker-compose-local.yml.gateway-service_ Compose Deployment.run.xml
  .run/docker-compose-local.yml.mail-service_ Compose Deployment.run.xml
  .run/docker-compose-local.yml.quiz-service_ Compose Deployment.run.xml
  .run/docker-compose-local.yml.report-service_ Compose Deployment.run.xml
  .run/docker-compose-local.yml.testing-service_ Compose Deployment.run.xml
  api-gateway/src/main/kotlin/ru/surf/apigateway/configuration/CorsConfiguration.kt
  api-gateway/src/main/kotlin/ru/surf/apigateway/configuration/RouteConfiguration.kt
  api-gateway/src/main/resources/application-dev.yml
  api-gateway/src/main/resources/application-prod.yml
  auth/src/main/kotlin/ru/surf/auth/configuration/CorsConfiguration.kt
  core/src/main/kotlin/ru/surf/core/configuration/CorsConfiguration.kt
  core/src/main/kotlin/ru/surf/core/configuration/SecurityConfiguration.kt
  core/src/main/resources/application-dev.yml
  core/src/main/resources/application-prod.yml
  core/src/main/resources/db/migration/core/V1.0.0__initial_script.sql
  docker-compose-local.yml
  external-files/src/main/kotlin/ru/surf/externalfiles/configuration/CorsConfiguration.kt
  external-files/src/main/resources/application-dev.yml
  external-files/src/main/resources/application-prod.yml
  external-files/src/main/resources/db/migration/external-files/V1.0.0__initial_script.sql
  web/src/app/service/candidate.service.ts
  web/src/app/service/event.service.ts
  web/src/app/service/resource.service.ts
Labels: fix

#34 TASK-253 Refactor kafka logic in service core
  core/src/main/kotlin/ru/surf/core/configuration/KafkaTopicConfiguration.kt
  core/src/main/kotlin/ru/surf/core/dto/GeneralNotificationDto.kt
  core/src/main/kotlin/ru/surf/core/event/ReceivingRequestKafkaEvent.kt
  core/src/main/kotlin/ru/surf/core/service/KafkaService.kt
  core/src/main/kotlin/ru/surf/core/service/impl/CandidateServiceImpl.kt
  core/src/main/kotlin/ru/surf/core/service/impl/KafkaServiceImpl.kt
  docker-compose-local.yml
Labels: refactor

#37 TASK-74 ci/cd preparations
  .gitignore
  .run/SurfWebStudyJam2022 [_core_bootJar].run.xml
  .run/docker-compose-local.yml_ Compose Deployment.run.xml
  .template.env
  auth/build.gradle.kts
  auth/src/main/resources/application-dev.yml
  auth/src/main/resources/application-prod.yml
  core/build.gradle.kts
  core/src/main/resources/application-prod.yml
  defenceOfProject/build.gradle.kts
  docker-compose.yml
  domain/build.gradle.kts
  external-files/build.gradle.kts
  external-files/src/main/resources/application-dev.yml
  mail/build.gradle.kts
  quiz/build.gradle.kts
  report/build.gradle.kts
  testing/build.gradle.kts
  testing/src/main/resources/application-prod.yml
  web/.gitignore
  web/angular.json
  web/src/app/app.component.less
  web/src/app/component/enroll/enroll-success/enroll-success.component.less
  web/src/app/service/candidate.service.ts
  web/src/app/service/event.service.ts
  web/src/app/service/resource.service.ts
  web/src/environments/environment.ts
Labels: enhancement

#39 TASK-73 Refactor external-files module
  external-files/build.gradle.kts
  external-files/src/main/kotlin/ru/surf/externalfiles/controller/ResourceController.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/controller/S3FileController.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/dto/PostResponseDto.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/mapper/S3FileMapper.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/mapper/impl/S3FileMapperImpl.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/repository/S3FileRepository.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/service/ResourceFileService.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/service/S3DatabaseService.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/service/S3FacadeService.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/service/S3FileService.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/service/S3RequestService.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/service/impl/ResourceFileServiceImpl.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/service/impl/S3DatabaseServiceImpl.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/service/impl/S3FacadeServiceImpl.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/service/impl/S3FileServiceImpl.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/service/impl/S3RequestServiceImpl.kt
Labels: refactor

#40 TASK-76 Add candidate filtering
  core/src/main/kotlin/ru/surf/core/service/CandidateFilterService.kt
  core/src/main/kotlin/ru/surf/core/service/CandidateService.kt
  core/src/main/kotlin/ru/surf/core/service/impl/CandidateFilterServiceImpl.kt
  core/src/main/kotlin/ru/surf/core/service/impl/CandidateServiceImpl.kt
  core/src/main/kotlin/ru/surf/core/util/FileUtil.kt
  core/src/main/resources/keywords/JAVA_BACKEND_KEYWORDS.txt
  web/src/app/component/enroll/enroll-applyment/enroll-applyment.component.html
Labels: enhancement

#42 TASK-78 concept of messaging with core and microservices via kafka
  core/src/main/kotlin/ru/surf/core/configuration/KafkaTopicConfiguration.kt
  core/src/main/kotlin/ru/surf/core/event/ReceivingRequestKafkaEvent.kt
  core/src/main/kotlin/ru/surf/core/service/KafkaService.kt
  core/src/main/kotlin/ru/surf/core/service/impl/CandidateServiceImpl.kt
  core/src/main/kotlin/ru/surf/core/service/impl/KafkaServiceImpl.kt
  docker-compose.yml
  domain/src/main/kotlin/ru/surf/core/kafkaEvents/CandidateAppliedEvent.kt
  domain/src/main/kotlin/ru/surf/core/kafkaEvents/IMailEvent.kt
  mail/build.gradle.kts
  mail/src/main/kotlin/ru/surf/mail/MailApplication.kt
  mail/src/main/kotlin/ru/surf/mail/config/KafkaConfig.kt
  mail/src/main/kotlin/ru/surf/mail/controller/EmailListener.kt
  testing/build.gradle.kts
  testing/src/main/kotlin/ru/surf/testing/TestingApplication.kt
  testing/src/main/kotlin/ru/surf/testing/config/KafkaConfig.kt
  testing/src/main/kotlin/ru/surf/testing/controller/TestingListener.kt
Labels: enhancement

#43 TASK-340 Add candidate filtering domain
  core/src/main/kotlin/ru/surf/core/controller/EventController.kt
  core/src/main/kotlin/ru/surf/core/repository/CandidateRepository.kt
  core/src/main/kotlin/ru/surf/core/service/CandidateService.kt
  core/src/main/kotlin/ru/surf/core/service/impl/CandidateServiceImpl.kt
Labels: refactor

#44 TASK-341 Fix merge conflicts problem
  core/src/main/kotlin/ru/surf/core/service/impl/CandidateServiceImpl.kt
Labels: fix

#45 TASK-75 Refactor excel parsing
  core/build.gradle.kts
  core/src/main/kotlin/ru/surf/core/configuration/HessianConfiguration.kt
  core/src/main/kotlin/ru/surf/core/controller/EventController.kt
  core/src/main/kotlin/ru/surf/core/dto/CandidateEventNotificationDto.kt
  core/src/main/kotlin/ru/surf/core/repository/EventRepository.kt
  core/src/main/kotlin/ru/surf/core/repository/EventTagRepository.kt
  core/src/main/kotlin/ru/surf/core/service/CandidateService.kt
  core/src/main/kotlin/ru/surf/core/service/EventTagService.kt
  core/src/main/kotlin/ru/surf/core/service/impl/CandidateFilterServiceImpl.kt
  core/src/main/kotlin/ru/surf/core/service/impl/CandidateServiceImpl.kt
  core/src/main/kotlin/ru/surf/core/service/impl/EventServiceImpl.kt
  core/src/main/kotlin/ru/surf/core/service/impl/EventTagServiceImpl.kt
  core/src/main/kotlin/ru/surf/core/service/impl/EventTypeServiceImpl.kt
  core/src/main/resources/application-dev.yml
  domain/src/main/kotlin/ru/surf/core/kafkaEvents/CandidateAppliedEvent.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/configuration/HessianConfiguration.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/controller/ResourceController.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/dto/CandidateExcelDto.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/service/ResourceFileService.kt
  external-files/src/main/kotlin/ru/surf/externalfiles/service/impl/ResourceFileServiceImpl.kt
Labels: enhancement, refactor
