Repository YaroslavBerezin/SurfWebStudyJam2022, pull requests merged in 2023-01, with the labels that each got.

#1 TASK-31 Clean Project
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/kotlin/ru/surf/web/studyjam/StudyJamApplication.kt
  src/main/kotlin/ru/surf/web/studyjam/jpa/entity/package-info.java
  src/main/kotlin/ru/surf/web/studyjam/jpa/repository/package-info.java
  src/main/kotlin/ru/surf/web/studyjam/service/package-info.java
  src/main/kotlin/ru/surf/web/studyjam/web/dto/package-info.java
  src/main/kotlin/ru/surf/web/studyjam/web/rest/HelloWorldController.kt
  src/main/kotlin/ru/surf/web/studyjam/web/rest/package-info.java
  src/main/resources/application.yml
  src/main/resources/db/migration/V1.0__initial_script.sql
  src/test/kotlin/ru/surf/web/studyjam/StudyJamApplicationTests.kt
Labels: refactor

#3 TASK-80 Fix core module
  core/settings.gradle.kts
Labels: bug

#4 TASK-8 Add empty Report module
  report/build.gradle.kts
  report/gradle/wrapper/gradle-wrapper.jar
  report/gradle/wrapper/gradle-wrapper.properties
  report/settings.gradle.kts
  report/src/main/kotlin/ru/surf/report/ReportApplication.kt
  report/src/main/resources/application.properties
  report/src/test/kotlin/ru/surf/report/ReportApplicationTests.kt
  settings.gradle.kts
Labels: enhancement

#5 TASK-44 Add empty external-files module
  external-files/build.gradle.kts
  external-files/gradle/wrapper/gradle-wrapper.jar
  external-files/gradle/wrapper/gradle-wrapper.properties
  external-files/settings.gradle.kts
  external-files/src/main/kotlin/ru/surf/externalfiles/ExternalFilesApplication.kt
  external-files/src/main/resources/application.yml
  external-files/src/main/resources/db/migration/V1.0__initial_script.sql
  external-files/src/test/kotlin/ru/surf/externalfiles/ExternalFilesApplicationTests.kt
Labels: enhancement

#9 TASK-32 Add initial migration script and test docker db
  core/build.gradle.kts
  core/src/main/resources/application.yml
  core/src/main/resources/db/migration/V1.0__initial_script.sql
  docker/docker-compose.yml
Labels: enhancement

#12 fetaure/task-47-add-defenceOfProject-module
  defenceOfProject/build.gradle.kts
  defenceOfProject/gradle/wrapper/gradle-wrapper.jar
  defenceOfProject/gradle/wrapper/gradle-wrapper.properties
  defenceOfProject/settings.gradle.kts
  defenceOfProject/src/main/kotlin/ru/surf/defenceofproject/DefenceOfProjectApplication.kt
  defenceOfProject/src/main/resources/application.properties
  defenceOfProject/src/test/kotlin/ru/surf/defenceofproject/DefenceOfProjectApplicationTests.kt
  settings.gradle.kts
Labels: enhancement

#10 TASK-46 Add database functionality
  core/build.gradle.kts
  core/docker-compose.yml
  core/src/main/kotlin/ru/surf/core/entity/Account.kt
  core/src/main/kotlin/ru/surf/core/entity/Answer.kt
  core/src/main/kotlin/ru/surf/core/entity/Candidate.kt
  core/src/main/kotlin/ru/surf/core/entity/Event.kt
  core/src/main/kotlin/ru/surf/core/entity/EventType.kt
  core/src/main/kotlin/ru/surf/core/entity/Question.kt
  core/src/main/kotlin/ru/surf/core/entity/QuestionType.kt
  core/src/main/kotlin/ru/surf/core/entity/Role.kt
  core/src/main/kotlin/ru/surf/core/entity/StateType.kt
  core/src/main/kotlin/ru/surf/core/entity/StatesEvents.kt
  core/src/main/kotlin/ru/surf/core/entity/SurfEmployee.kt
  core/src/main/kotlin/ru/surf/core/entity/Team.kt
  core/src/main/kotlin/ru/surf/core/entity/TeamFeedback.kt
  core/src/main/kotlin/ru/surf/core/entity/Test.kt
  core/src/main/kotlin/ru/surf/core/entity/Trainee.kt
  core/src/main/kotlin/ru/surf/core/entity/TraineeFeedback.kt
  core/src/main/kotlin/ru/surf/core/entity/base/BaseEntity.kt
  core/src/main/kotlin/ru/surf/core/entity/base/UUIDBasedEntity.kt
  core/src/main/kotlin/ru/surf/core/repository/AccountRepository.kt
  core/src/main/kotlin/ru/surf/core/repository/AnswerRepository.kt
  core/src/main/kotlin/ru/surf/core/repository/CandidateRepository.kt
  core/src/main/kotlin/ru/surf/core/repository/EventRepository.kt
  core/src/main/kotlin/ru/surf/core/repository/EventTypeRepository.kt
  core/src/main/kotlin/ru/surf/core/repository/QuestionRepository.kt
  core/src/main/kotlin/ru/surf/core/repository/RoleRepository.kt
  core/src/main/kotlin/ru/surf/core/repository/StateTypeRepository.kt
  core/src/main/kotlin/ru/surf/core/repository/StatesEventsRepository.kt
  core/src/main/kotlin/ru/surf/core/repository/SurfEmployeeRepository.kt
  core/src/main/kotlin/ru/surf/core/repository/TeamFeedbackRepository.kt
  core/src/main/kotlin/ru/surf/core/repository/TeamRepository.kt
  core/src/main/kotlin/ru/surf/core/repository/TestRepository.kt
  core/src/main/kotlin/ru/surf/core/repository/TraineeFeedbackRepository.kt
  core/src/main/kotlin/ru/surf/core/repository/TraineeRepository.kt
  core/src/main/resources/application.yml
  core/src/main/resources/db/migration/V1.0.0__initial_script.sql
  core/src/main/resources/db/migration/V1.0__initial_script.sql
Labels: enhancement

#14 TASK-49 Add OpenAPI 3 support
  core/build.gradle.kts
  core/src/main/kotlin/ru/surf/core/configuration/SwaggerConfiguration.kt
  core/src/main/resources/application.yml
Labels: documentation

#16 TASK-51 Fix entities issues
  core/src/main/kotlin/ru/surf/core/entity/Account.kt
  core/src/main/kotlin/ru/surf/core/entity/Answer.kt
  core/src/main/kotlin/ru/surf/core/entity/Candidate.kt
  core/src/main/kotlin/ru/surf/core/entity/EventType.kt
  core/src/main/kotlin/ru/surf/core/entity/Question.kt
  core/src/main/kotlin/ru/surf/core/entity/QuestionType.kt
  core/src/main/kotlin/ru/surf/core/entity/Role.kt
  core/src/main/kotlin/ru/surf/core/entity/StateType.kt
  core/src/main/kotlin/ru/surf/core/entity/StatesEvents.kt
  core/src/main/kotlin/ru/surf/core/entity/SurfEmployee.kt
  core/src/main/kotlin/ru/surf/core/entity/Team.kt
  core/src/main/kotlin/ru/surf/core/entity/TeamFeedback.kt
  core/src/main/kotlin/ru/surf/core/entity/Test.kt
  core/src/main/kotlin/ru/surf/core/entity/Trainee.kt
  core/src/main/kotlin/ru/surf/core/entity/TraineeFeedback.kt
Labels: fix
